### ISSUE TITLE
It shows me my statistics but the input for live data doesn't work?

### ISSUE THREAD

**Issue by PatafixPLTX** [Swackles/the-finals-tracker#2]
I used your `the-finals-tracker-extractor` to extract my ID. This works perfectly but when I pass this into `the-finals-tracker` input for live data, it doesn't work, there's nothing. So I manually moved my data from `responses` to `mockedGameStats.json` and the page shows me my stats in the `mocked data` section.
So I don't know if it's normal that it doesn't work, but I do appreciate the project ! Good work !
![image](https://github.com/Swackles/the-finals-tracker/assets/87929402/73511899-5589-4445-9c81-a76b08071971)

**Comment by Swackles** [comment]
Ty and glad to see you were able to figure out without docs 😃 

Right now the website is not functional as I'm in the middle of rewriting large parts of it. I'm hoping to have a new functional version up and running by the end of the week. I'll leave this open and let you know here.

**Comment by PatafixPLTX** [comment]
Ok nice ! Good luck !

**Comment by Swackles** [comment]
Okey, so I did a rush job to get it out. Currently accessible in https://www.finals-tracker.com/

**Comment by PatafixPLTX** [comment]
![image](https://github.com/Swackles/the-finals-tracker/assets/87929402/82f28c42-16de-4b0e-a984-bd9e6f0258ac)
![image](https://github.com/Swackles/the-finals-tracker/assets/87929402/c697e430-c7e1-4003-89f0-13d7c2b83bb3)
Nice ! You're so determined !

**Comment by Swackles** [comment]
Ty, it's far from good, but hopefully can get there at some point

**Comment by PatafixPLTX** [comment]
If I have the time, I could help you a little, but I'm no TypeScript whiz, but I've got a friend who'd love it.

**Comment by Swackles** [comment]
Actually, I was wrong, it seems they have renamed it. This game took place on the 20th of december

![image](https://github.com/Swackles/the-finals-tracker/assets/25078482/7a87b5f6-5651-48ef-91d9-eb1037b6423a)
